const DEFAULT_ERROR = "默认";
const NAME_OR_PASSWORD_IS_NULL = "用户名或密码不能为空";
const MOBILE_PHONE_NUMBER_FORMAT_IS_INCORRECT = "手机号码格式错误";
const PASSWORD_FORMAT_IS_INCORRECT = "密码格式错误，需要字母数字组合";
const USER_IS_EXIST = "用户已存在";
const SERVER_ERROR = "服务器错误";
const USER_IS_NOT_EXIST = "用户不存在";
const WRONG_PASSWORD = "密码错误";
const NO_ACCESS = "没有访问权限";
const ACCOUNT_EXPIRED = "账号过期，请重新登录";
const PLEASE_ENTER_THE_STORE_NAME = "店铺名称首尾不能包含空格，且必须是字符串";
const PLEASE_ENTER_THE_STORE_ADDRESS = "店铺地址首尾不能包含空格，且必须是字符串";
const PLEASE_UPLOAD_THE_STORE_LOGO = "请上传店铺logo";
const MERCHANT_ALREADY_EXISTS = "商家已存在";
const ID_IS_NULL = "id不能为空";
const CANNOT_CANTAIN_SPACES = "不能包含空格";
const DATA_FORMAT_ERROR = "数据格式错误";
const CATEGORY_IS_EXIST = "菜品类目已存在";
const DISHUNIT_IS_EXIST = "单位已存在";
const OBJECT_VALUE_IS_INVALID = "对象值不合法";
const CATEGORY_MUST_BE_STRING = "分类必须是string类型";
const IMAGE_FORMAT_ERROR = "图片数据格式错误";
const DISHNAME_TYPE_ERROR = "菜品名称类型错误,必须是string类型";
const DISHUNITPRICE_TYPE_ERROR = "菜品价格类型错误,必须是string类型";
const DISHUNIT_TYPE_ERROR = "菜品单位类型错误,必须是string";
const DISHCID_TYPE_ERROR = "菜品CID错误";
const DISH_IS_EXIST = "菜品已存在";
const DISH_IS_NOT_EXIST = "菜品不存在";
const TABLE_NUMBER_ALREADY_EXISTS = "桌号已经存在";
const ORDER_IS_NOT_EXIST = "订单不存在";

module.exports = {
  NAME_OR_PASSWORD_IS_NULL,
  MOBILE_PHONE_NUMBER_FORMAT_IS_INCORRECT,
  PASSWORD_FORMAT_IS_INCORRECT,
  USER_IS_EXIST,
  SERVER_ERROR,
  USER_IS_NOT_EXIST,
  WRONG_PASSWORD,
  NO_ACCESS,
  ACCOUNT_EXPIRED,
  PLEASE_ENTER_THE_STORE_NAME,
  PLEASE_ENTER_THE_STORE_ADDRESS,
  PLEASE_UPLOAD_THE_STORE_LOGO,
  MERCHANT_ALREADY_EXISTS,
  ID_IS_NULL,
  CANNOT_CANTAIN_SPACES,
  DATA_FORMAT_ERROR,
  CATEGORY_IS_EXIST,
  DISHUNIT_IS_EXIST,
  OBJECT_VALUE_IS_INVALID,
  CATEGORY_MUST_BE_STRING,
  IMAGE_FORMAT_ERROR,
  DISHNAME_TYPE_ERROR,
  DISHUNITPRICE_TYPE_ERROR,
  DISHUNIT_TYPE_ERROR,
  DISHCID_TYPE_ERROR,
  DISH_IS_EXIST,
  DISH_IS_NOT_EXIST,
  TABLE_NUMBER_ALREADY_EXISTS,
  ORDER_IS_NOT_EXIST
};
